In [1]:
import numpy as np

In [10]:
x = np.arange(100, dtype=float)

In [11]:
def derivative_loop(x):
    derivative = np.empty(len(x)-1)
    for i, x_i in enumerate(x[:-1]):
        derivative[i] = x[i+1] - x_i
    return derivative


In [12]:
derivative_loop(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
def derivative_slice(x):
    return x[1:] - x[:-1]

In [14]:
derivative_slice(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
%timeit derivative_loop(x)

32.7 µs ± 237 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
%timeit derivative_slice(x)

1.04 µs ± 32.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Scientific computing

In [17]:
x = np.arange(15, dtype=float).reshape(5, 3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [18]:
x.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [19]:
x.ravel(order='K')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

**Let us work with the transpose**

In [21]:
x.T   # x' in MATLAB

array([[ 0.,  3.,  6.,  9., 12.],
       [ 1.,  4.,  7., 10., 13.],
       [ 2.,  5.,  8., 11., 14.]])

In [23]:
x.T.ravel()

array([ 0.,  3.,  6.,  9., 12.,  1.,  4.,  7., 10., 13.,  2.,  5.,  8.,
       11., 14.])

In [24]:
x.T.ravel('K')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [25]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
x.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# Be careful with mutables

In [28]:
y = x
print(x)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


In [29]:
y[2, 2] = -5

In [30]:
print(x)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7. -5.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


In [31]:
x is y

True

**This is also true for lists**

In [32]:
l = [1, 2, [1, 2]]
ll = l
print(l)

[1, 2, [1, 2]]


In [33]:
ll[1] = -5
print(l)

[1, -5, [1, 2]]


**Solution: copying**

Remember `x` is an array

In [34]:
y = x.copy()

In [35]:
y[1, 1] = 100

In [36]:
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7., -5.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [37]:
y


array([[  0.,   1.,   2.],
       [  3., 100.,   5.],
       [  6.,   7.,  -5.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

For builtins, we don't have a copy method. Instead, we use the builtin copy module

In [38]:
import copy

In [39]:
l = [1, 2, [1, 2]]
l_copy = copy.copy(l)

In [40]:
l_copy[1] = 5

In [41]:
l

[1, 2, [1, 2]]

In [42]:
l_copy[2][0] = 5

In [43]:
l_copy

[1, 5, [5, 2]]

In [44]:
l

[1, 2, [5, 2]]

In [45]:
l_deepcopy = copy.deepcopy(l)

In [46]:
l_deepcopy[2][0] = 100

In [47]:
l_deepcopy

[1, 2, [100, 2]]

In [48]:
l

[1, 2, [5, 2]]

## Another aside: The mutable default trap

In [49]:
def f(input_list=[]):
    input_list.append(1)
    print(input_list)

In [50]:
f([-1])

[-1, 1]


In [51]:
f()

[1]


In [52]:
f()

[1, 1]


In [53]:
def f(input_list=None):
    if input_list is None:
        input_list = []

    input_list.append(1)
    print(input_list)

# Back to arrays

In [54]:
y = np.arange(30).reshape(2, 5, 3)
y2 = np.rollaxis(y, 1, 0)

In [55]:
y.shape

(2, 5, 3)

In [56]:
y2.shape

(5, 2, 3)

Currently, nothing is copied, the memory layout is strange

In [57]:
%timeit y2.reshape(5, -1)

765 ns ± 26.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [60]:
%timeit y.reshape(2, -1)

301 ns ± 5.23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Going from Fortran style to C style and vice versa

In [61]:
x = np.random.standard_normal((100, 100))

In [62]:
y = np.ascontiguousarray(x)  # Useful to load from MATLAB

In [64]:
z = np.asfortranarray(y)  # Seldomly useful unless you interface with Fortran yourselves

# Linear algebra in Python

In [66]:
X = np.random.standard_normal((100, 5))
w = np.random.standard_normal((5, 1))

In [67]:
# Before Python 3.5:
y = X.dot(w)
y = np.dot(X, w)

# After Python 3.5:
y = X@w

Other linear algebra tools are in `numpy.linalg`

In [68]:
np.linalg.norm(y)

8.666836267008927

It's tedious to write `np.linalg` all the time

In [69]:
import numpy.linalg as la

In [70]:
la.norm(y)

8.666836267008927

In [71]:
U, s, Vt = la.svd(X, full_matrices=False)  # Economy style SVD

In [75]:
w_approx = la.lstsq(X, y)[0]

/home/yngvem/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [78]:
w_approx - w

array([[-1.66533454e-16],
       [-1.11022302e-16],
       [ 6.10622664e-16],
       [-8.32667268e-17],
       [-1.11022302e-16]])

# Broadcasting
## How NumPy deals with singleton axes

In [79]:
w.shape

(5, 1)

In [80]:
X.mean()

2.7794669005416493e-05

In [81]:
X.mean(axis=0)

array([ 0.02186431, -0.01583473, -0.14649088,  0.04435263,  0.09624764])

In [84]:
X.mean(0).shape   # X.mean(0) == X.mean(axis=0)

(5,)

In [85]:
X_centered = X - X.mean(0)

To figure out how this works, we'll look at how NumPy deals with singletons

In [87]:
X_mean_0 = X.mean(0, keepdims=True)
X_mean_0.shape

(1, 5)

In [88]:
X_mean_1 = X.mean(1, keepdims=True)
X_mean_1.shape

(100, 1)

In [89]:
X_centered_0 = X - X_mean_0

X_centered_0.mean(0)

array([-5.21804822e-17, -3.99680289e-17,  1.27675648e-17,  5.55111512e-18,
        1.11022302e-17])

In [91]:
X_centered_1 = X - X_mean_1

X_centered_1.mean(1)

array([ 0.00000000e+00, -1.11022302e-17, -2.22044605e-17,  0.00000000e+00,
       -2.22044605e-17,  2.22044605e-17,  0.00000000e+00,  1.11022302e-17,
        3.33066907e-17, -5.55111512e-17, -1.77635684e-16, -1.11022302e-17,
        2.22044605e-17, -4.44089210e-17,  4.44089210e-17, -8.88178420e-17,
        1.77635684e-16, -2.22044605e-17,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.22044605e-17,  2.22044605e-17,  0.00000000e+00,
       -1.11022302e-16,  1.11022302e-17, -3.33066907e-17,  2.22044605e-17,
       -1.11022302e-17,  8.88178420e-17,  0.00000000e+00,  2.22044605e-17,
        0.00000000e+00, -7.77156117e-17,  0.00000000e+00,  4.44089210e-17,
       -4.44089210e-17,  0.00000000e+00,  6.66133815e-17,  2.22044605e-17,
       -4.44089210e-17, -4.44089210e-17, -4.44089210e-17,  4.44089210e-17,
        2.22044605e-17, -3.88578059e-17, -6.66133815e-17,  4.44089210e-17,
       -8.32667268e-17,  0.00000000e+00,  0.00000000e+00, -3.33066907e-17,
        3.33066907e-17, -

NumPy will always try to add singleton axes on the START of the shape to enable broadcasting

In [93]:
X_centered = X - X.mean(0)

In [94]:
X_row_centered = X - X.mean(1)

ValueError: operands could not be broadcast together with shapes (100,5) (100,) 